### ISSUE TITLE
`Rocks update` regression

### ISSUE THREAD

**Issue by Nsidorenco** [nvim-neorocks/rocks-git.nvim#81] opened 2024-11-19 21:17 UTC
At some point between version `2.3.1` and the newest something broke in my configuration making me unable to run `Rocks update`.

Output of `Rocks log`:
```
[START][2024-11-19 22:02:30] rocks.nvim logging initiated
ERROR | 2024-11-19 22:02:56 | .../.local/share/nvim/rocks/rocks_rtp/lua/rocks-git/git.lua:285 | {
  code = 1,
  signal = 0,
  stderr = "Failed to invoke git: ...unwrapped-nightly/share/nvim/runtime/lua/vim/_system.lua:253: ENOENT: no such file or directory"
}
```

From bisecting my `rocks.toml` it seems to be caused by the following:
```
[plugins."snacks.nvim"]
git = "folke/snacks.nvim"
rev = "v2.4.0"
```

**Comment by mrcjkb** [comment] 2024-11-20 06:12
hey 👋 

This is a duplicate of https://github.com/nvim-neorocks/rocks-git.nvim/issues/68.
It should have been fixed with version 2.4.1.

Closing this issue as a duplicate. Please ensure you are using version 2.4.1 of rocks-git.nvim and reopem #68 if you are still facing the issue 😄

**Closed by mrcjkb** 2024-11-20 06:12 UTC
